export const ENV_CONFIG = {
  MODE: 'MODE',
  DEV: 'DEV',
  VITE_BUILD_ENV: 'VITE_BUILD_ENV',
  /* sentry 相关 */
  VITE_DEBUG: 'VITE_DEBUG',
  VITE_SENTRY_ENABLED: 'VITE_SENTRY_ENABLED',
  VITE_SENTRY_DSN: 'VITE_SENTRY_DSN',
  VITE_MAX_BREADCRUMBS: 'VITE_MAX_BREADCRUMBS',
  VITE_SAMPLE_RATE: 'VITE_SAMPLE_RATE',

  /** elk 配置 */
  VITE_ELK_REPORT_URL: 'VITE_ELK_REPORT_URL',
  VITE_ELK_REPORT_INTERVAL: 'VITE_ELK_REPORT_INTERVAL',
  VITE_ELK_PLATFORM: 'VITE_ELK_PLATFORM',
}
